### ISSUE TITLE
Editing Schema name breaks graph

### ISSUE THREAD

**Issue by davidmw** [design-first/system-designer#113]
V3.1.0 on OSX

After creating a three node graph and a few components, I decided to change Node names to Mixed case and relationship names to lower case.

Changing schema names broke all inbound/outbound links and the components / component diagram.  Since renaming things is common during design work, handling this well would improve the product UX significantly.

**Comment by ecarriou** [comment]
It seems that when you rename a schema, it misses the renaming of the links/collections. So you need to do it manually to make it works. I will do a fix for that.

**Comment by ecarriou** [comment]
I have made some tests and you have all the informations about the renaming issues on the `Logs`  panel when you run the system. So you have all the informations to fix it manually waiting for an improvement on that part.

I have updated the documentation about the fact that `Nodes` and `Relationships` can not be changed for generation Graph diagram. I will close then this issue.
