### ISSUE TITLE
Push to GItHub fails

### ISSUE THREAD

**Issue by rniswonger** [design-first/system-designer#120]
Hello, 

Thank you for the great software! I'm having a little problem, though. I receive the message "GitHub: Invalid request. "sha" wasn't supplied." When I attempt to Push my system to GitHub from my laptop. Pull works fine on the device. Both Push and Pull work fine on my iPad using the same GitHub token.

System Designer version number: 3.3.0
System Designer platform: Windows
Your OS version: 10
Steps to reproduce the problem: 
 - Install software from MS Store. 
 - Setup GitHub token as described in the docs
 - Pull system (succeeds)
 - Push system (fails with error)

**Comment by ecarriou** [comment]
Thank you for reporting the issue! I am able to reproduce it. I will check where it comes from and will fix it.

**Comment by ecarriou** [comment]
I found the issue (related to the way browsers cache requests). A fix is coming soon.

**Comment by ecarriou** [comment]
I plan to publish a new version of System Designer on the stores this weekend. Depending on the validation process, it will be available at the end of next week I think.
