### ISSUE TITLE
Configuration Settings

### ISSUE THREAD

**Issue by dau710** [design-first/system-designer#128]
For issues give the following informations related to your problem: 

- [x] System Designer version number: (ex: *v3.5.1*)
- [x] System Designer platform: (ex: *macOS*)
- [x] Your OS version: (ex: *macOS 10.14*)
- [x] If use on a phone, please give the model: (ex: *iPhone X*)
- [x] Steps to reproduce the problem

note: if possible, send us the system you used.

**Comment by dau710** [comment]
Hi, I am using System Designer 3.3.3 on Macbook Air, Mojave 10.14.4 and iPad System Designer 3.3.0 on iPad 12.2.
The Configuration Setting on the System Designer for Macbook and iPad differ.  I can successfully import via the Macbook version but as the iPad version lacks the same Configuration Settings I am unable to successfully import or export.
Can you please assist me if I have missed something or let me know if this is a known issue.

**Comment by ecarriou** [comment]
Hi,

 if you want to import/export system with the iOS version of System Designer you will need to use the [GitHub module](https://designfirst.io/systemdesigner/documentation/docs/en/sync-your-system-with-github.html). You can also copy the JSON under the `Bundle` tab when you edit a system (i.e. if you click on a system) with the `Advanced mode` enabled.

Import has been removed on iOS version in favor of GitHub synchronization, but I can add this feature in a next release if you think it is a must have.

**Comment by dau710** [comment]
Hi,
The github module is on my macbook but that option does not appear to be on the ipad.  I had already added my github repository and generated password but when I try to access it from the ipad System Designer it says "github not found". I have copied the github url and generated password directly, can you please advise further.

**Comment by ecarriou** [comment]
Hi,  

did you have more information about the error message (i.e. the complete error message)? By the way, when you have set the Github repository value in the configuration panel, the format you set was like user_name/repository (i.e. not the url to the repository)? I have just tried the iOS version and the GitHub module seems to work. Anyway I will investigate your issue.

**Comment by dau710** [comment]
Hi,
I am only new to get him and programming but when I went to get help to get the repository link it gave me a link starting with HTTPS. So I had placed that into the system designer settings and I've now changed it and she said and it works. I really appreciate your kind help, thank you very much.
