### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by flasaracina** [design-first/system-designer#132]
Hello, some months ago I tried system designer on a Linux machine. I don't remember how I installed it but now every time I go to localhost:3000 system designer shows up.
How can I clean uninstall it from my computer?
Thanks

**Comment by ecarriou** [comment]
Hi,

  as described in the documentation, ports used by System Designer are:

- _8080_ when you start the app and
- _9001_ when you start the app in development mode.

So it is quite strange that you get the port _3000_ used for it.
Do you have the same result with another browser when you go to  localhost:3000? If so, it maybe means that System Designer has been installed as serviced worker at that port. To remove it, just empty the cache of your browser.

**Comment by flasaracina** [comment]
I already tried it but with no avail. Anyway it was on a VM and I don't remember why it was set up on port 3000, so being a problem on my part, feel free to close this issue. Thank you for your support
