### ISSUE TITLE
Components: Showing values from unrelated collections

### ISSUE THREAD

**Issue by mikeaustin** [design-first/system-designer#133]
**Describe the bug**
When on the Components tabs, after adding collection values, collections below other collections show the contents of the above collections. For example, Labels only has one item, but it displays two, one of which is a Comment, not a Label:

*Viewing the Component*

Field | Value
-- | --
Comments | [d03972db-6a5c-441f-8190-f0bf1912e531]
Labels | [d03972db-6a5c-441f-8190-f0bf1912e531,be527a82-917b-49b5-a652-096a4a7a125f]

*Editing the Component*:

	"Labels": [
		"be527a82-917b-49b5-a652-096a4a7a125f"
	],

**Expected behavior**
In the example above, the Labels field should not have d039... because that is a Comment. It's like the array used to get the data is being re-used and not cleared.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Firefox 69.0

**Comment by ecarriou** [comment]
Thank you for taking time to create the issue.

The bugs seems related to the way the UI construct the model, it does not affect the data itself. I will fix it ASAP.

**Comment by ecarriou** [comment]
The fix will be in release v4.0.2 of System Designer.

**Comment by mikeaustin** [comment]
Thank you so much! It's a very interesting project. I'm using it think about all the schemas I need for a project, and I like being able to enter data a click links to other tables to navigate around. I don't use any of the behavior stuff, since I'll be using a React/Apollo framework.
